import os
from typing import List, Dict

import psycopg
from psycopg.types.json import Jsonb
from pgvector.psycopg import register_vector


class PostgresStore:
    """Write embedded service snapshot rows back to Postgres inside a single transaction"""

    def __init__(self, table_name: str):
        self.table_name = table_name
        self.connection_string = os.getenv('DATABASE_URL')
        if not self.connection_string:
            raise ValueError(
                "DATABASE_URL environment variable is required.\n"
                "Add it to your .env file: DATABASE_URL=postgresql://user:password@host:port/dbname"
            )

    def write_all(self, rows: List[Dict], vectors: List[List[float]], batch_size: int) -> None:
        """
        Truncate the table and insert all rows with their embeddings in a single transaction.
        Other readers see the old data until commit — no downtime window.

        Args:
            rows:       All rows returned by the denormalization SQL (as dicts)
            vectors:    Embedding vectors in the same order as rows
            batch_size: Number of rows per executemany call
        """
        with psycopg.connect(self.connection_string) as conn:
            register_vector(conn)
            with conn.cursor() as cur:
                cur.execute(f"TRUNCATE {self.table_name}")

                for i in range(0, len(rows), batch_size):
                    batch_rows = rows[i:i + batch_size]
                    batch_vectors = vectors[i:i + batch_size]
                    self._insert_batch(cur, batch_rows, batch_vectors)

            conn.commit()

    def _insert_batch(self, cur, rows: List[Dict], vectors: List[List[float]]) -> None:
        """
        Insert a batch of rows with their embedding vectors using executemany.

        The `schedule` column is jsonb — wrapped in Jsonb() so psycopg3
        serializes it correctly. All other array columns are handled natively.
        id is excluded — it is bigserial and auto-generated by Postgres.
        """
        data = [
            (
                row['service_id'],
                row['resource_id'],
                row['program_id'],
                row['address_id'],
                row['verified_at'],
                row['updated_at'],
                row['latitude'],
                row['longitude'],
                Jsonb(row['schedule']) if row['schedule'] is not None else None,
                row['category_ids'],
                row['category_names'],
                row['parent_category_names'],
                row['sfsg_category_ids'],
                row['sfsg_category_names'],
                row['ucsf_top_category_ids'],
                row['ucsf_top_category_names'],
                row['ucsf_sub_category_ids'],
                row['ucsf_sub_category_names'],
                row['our415_category_ids'],
                row['our415_category_names'],
                row['eligibility_age'],
                row['eligibility_education'],
                row['eligibility_employment'],
                row['eligibility_ethnicity'],
                row['eligibility_family_status'],
                row['eligibility_financial'],
                row['eligibility_gender'],
                row['eligibility_health'],
                row['eligibility_immigration'],
                row['eligibility_housing'],
                row['eligibility_other'],
                row['eligibility_all'],
                row['embedding_text'],
                vector,
            )
            for row, vector in zip(rows, vectors)
        ]

        cur.executemany(
            f"""
            INSERT INTO {self.table_name} (
                service_id, resource_id, program_id, address_id,
                verified_at, updated_at, latitude, longitude, schedule,
                category_ids, category_names, parent_category_names,
                sfsg_category_ids, sfsg_category_names,
                ucsf_top_category_ids, ucsf_top_category_names,
                ucsf_sub_category_ids, ucsf_sub_category_names,
                our415_category_ids, our415_category_names,
                eligibility_age, eligibility_education, eligibility_employment,
                eligibility_ethnicity, eligibility_family_status, eligibility_financial,
                eligibility_gender, eligibility_health, eligibility_immigration,
                eligibility_housing, eligibility_other, eligibility_all,
                embedding_text, embedding
            ) VALUES (
                %s, %s, %s, %s,
                %s, %s, %s, %s, %s,
                %s, %s, %s,
                %s, %s,
                %s, %s,
                %s, %s,
                %s, %s,
                %s, %s, %s,
                %s, %s, %s,
                %s, %s, %s,
                %s, %s, %s,
                %s, %s
            )
            """,
            data,
        )
